In [1]:
import os
import pandas as pd
from time import sleep
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select

%config Completer.use_jedi = False

In [2]:
df_1 = pd.read_csv('./processed_station_geo_loc.csv')
df_2 = pd.read_csv('./stations_region.csv')
df = pd.merge(df_1, df_2, on='name')
df.head()

,id,name,latitude,longitude,state,city
0,site_5094,"SIDCO Kurichi, Coimbatore - TNPCB",10.942451,76.978996,Tamil Nadu,Coimbatore
1,site_5261,"Muradpur, Patna - BSPCB",25.619651,85.147382,Bihar,Patna
2,site_5044,"Municipal Corporation Office, Dharuhera - HSPCB",28.206800,76.799700,Haryana,Dharuhera
3,site_5072,"Rishi Nagar, Kaithal - HSPCB",29.800600,76.415500,Haryana,Kaithal
4,site_163,"Peenya, Bengaluru - CPCB",13.027020,77.494094,Karnataka,Bengaluru

In [3]:
df.sort_values(['state', 'city'], inplace=True)

In [4]:
df.reset_index(drop=True, inplace=True)

In [5]:
df.values[100]

array(['site_1429', 'Nehru Nagar, Delhi - DPCC', 28.567890000000002,
       77.25051500000001, 'Delhi', 'Delhi'], dtype=object)

In [8]:
for idx in range(len(df)):
    
    state = df.state[idx]
    city = df.city[idx]
    station_id = df.id[idx]
    station_name = df.name[idx]
    
    print(f"{idx}. {state} :: {city} :: {station_id} :: {station_name} :: ", end='')
    break

0. Andhra Pradesh :: Amaravati :: site_1406 :: Secretariat, Amaravati - APPCB ::

In [4]:
def fill_data(field_name, value):
    
    if field_name == 'state':
        field_box_click = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[1]'
        field_box_text = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/select-dropdown/div/div[1]/input'
        text = value
        
    elif field_name == 'city':
        field_box_click = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/div/div/div[1]'
        field_box_text = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/select-dropdown/div/div[1]/input'
        text = value
        
    elif field_name == 'station':
        field_box_click = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[3]/div/ng-select/div/div/div[1]'
        field_box_text = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[3]/div/ng-select/select-dropdown/div/div[1]/input'
        text = value
        
    if value=='Noida':
        field_box_click_action = driver.find_element_by_xpath(field_box_click)
        field_box_click_action.click()
        
        field_box_text_action = driver.find_element_by_xpath(field_box_text)
        field_box_text_action.send_keys(text)

        city_click = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/select-dropdown/div/div[2]/ul/li[2]')
        city_click.click()
        
    else:
        field_box_click_action = driver.find_element_by_xpath(field_box_click)
        field_box_click_action.click()

        field_box_text_action = driver.find_element_by_xpath(field_box_text)
        field_box_text_action.send_keys(text)

        field_box_text_action.send_keys(Keys.ENTER)

In [5]:
driver = webdriver.Chrome('/usr/bin/chromedriver')

In [6]:
driver.get('https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing')

In [7]:
driver.get('https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing/caaqm-data-availability')
sleep(15)

In [8]:
root_dir = "./stations_start_info"
if not os.path.exists(root_dir):
    os.mkdir(root_dir)

In [9]:
dummy_df = pd.read_csv(os.path.join(root_dir,"dummy.csv"))

In [ ]:
error_idx = []
for idx in range(len(df)):
    
    state = df.state[idx]
    city = df.city[idx]
    station_id = df.id[idx]
    station_name = df.name[idx]
    
    print(f"{idx}. {state} :: {city} :: {station_id} :: {station_name} :: ", end='')
    
    file_path = os.path.join(root_dir, state)
    if not os.path.exists(file_path):
        os.mkdir(file_path)
        
    
    # Find the button using XPath and click it
    # Clearing previous details filled in each field
    button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[2]')
    button.click()
    
    sleep(1)
    
    fill_data(field_name='state', value=state)
    sleep(1)
    fill_data(field_name='city', value=city)
    sleep(1)
    fill_data(field_name='station', value=station_name)
    sleep(1)
    
    # Find the button using XPath and click it
    button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[4]/div/button')
    button.click()
    
    sleep(20)
    
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    table = soup.find('table', {'class': 'table-hover'})
    
    headers = []
    rows = []
    for tr in table.tbody.find_all('tr'):
        row = []
        for td in tr.find_all('td'):
            row.append(td.text.strip())
        rows.append(row)

    for th in table.thead.find_all('th'):
        headers.append(th.text.strip())
        
    df_1 = pd.DataFrame(rows, columns=headers)
    
    if df_1.equals(dummy_df):
        print("ERROR", end='\n\n')
        error_idx.append(idx)
#         break
    else:
        df_1.to_csv(os.path.join(file_path, city + '_' + station_id + '.csv'), header=True, index=False)
        print('Data Saved')
        dummy_df = df_1
    
    
#     break

0. Tamil Nadu :: Coimbatore :: site_5094 :: SIDCO Kurichi, Coimbatore - TNPCB :: Data Saved
1. Bihar :: Patna :: site_5261 :: Muradpur, Patna - BSPCB :: Data Saved
2. Haryana :: Dharuhera :: site_5044 :: Municipal Corporation Office, Dharuhera -  HSPCB :: Data Saved
3. Haryana :: Kaithal :: site_5072 :: Rishi Nagar, Kaithal - HSPCB :: Data Saved
4. Karnataka :: Bengaluru :: site_163 :: Peenya, Bengaluru - CPCB :: Data Saved
5. Uttar Pradesh :: Moradabad :: site_5613 :: Transport Nagar, Moradabad - UPPCB :: Data Saved
6. Uttar Pradesh :: Noida :: site_5123 :: Sector-1, Noida - UPPCB :: Data Saved
7. Madhya Pradesh :: Satna :: site_1433 :: Bandhavgar Colony, Satna - Birla Cement :: Data Saved
8. Maharashtra :: Mumbai :: site_5413 :: Mulund West, Mumbai - MPCB :: Data Saved
9. Haryana :: Palwal  :: site_5050 :: Shyam Nagar, Palwal - HSPCB :: Data Saved
10. Karnataka :: Hassan :: site_5448 :: B.Katihalli, Hassan - KSPCB :: Data Saved
11. Sikkim :: Gangtok :: site_5590 :: Zero Point GICI, Gangtok - SSPCB ::

In [10]:
df_1.equals(df_1)

True

In [9]:
df_1 == df_1

,Year,January,February,March,April,May,June,July,August,September,October,November,December
0,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True,True,True

In [10]:
# Find the button using XPath and click it
button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[2]')
button.click()

In [11]:
# Find the button using XPath and click it
button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[1]')
button.click()

In [12]:
state_field = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/select-dropdown/div/div[1]/input')
state_field.send_keys('Uttar Pradesh')

In [13]:
# Press Enter key
state_field.send_keys(Keys.ENTER)

In [16]:
# Find the button using XPath and click it
button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/div/div/div[1]')
button.click()

In [24]:
city_field = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/select-dropdown/div/div[1]/input')
city_field.send_keys('Noida')

In [41]:
city_click = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/select-dropdown/div/div[2]/ul/li[2]')
city_click.click()

In [17]:
# Press Enter key
city_field.send_keys(Keys.ENTER)

In [18]:
# Find the button using XPath and click it
button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[3]/div/ng-select/div/div/div[1]')
button.click()

In [19]:
station_field = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[3]/div/ng-select/select-dropdown/div/div[1]/input')
station_field.send_keys('Secretariat, Amaravati - APPCB')

In [20]:
# Press Enter key
station_field.send_keys(Keys.ENTER)

In [21]:
# Find the button using XPath and click it
button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[4]/div/button')
button.click()

In [7]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [8]:
table = soup.find('table', {'class': 'table-hover'})

In [9]:
table

<table _ngcontent-c3="" class="table table-hover">
<thead _ngcontent-c3="">
<tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "Year,January,February,March,Ap"
}--><th _ngcontent-c3="">Year</th><th _ngcontent-c3="">January</th><th _ngcontent-c3="">February</th><th _ngcontent-c3="">March</th><th _ngcontent-c3="">April</th><th _ngcontent-c3="">May</th><th _ngcontent-c3="">June</th><th _ngcontent-c3="">July</th><th _ngcontent-c3="">August</th><th _ngcontent-c3="">September</th><th _ngcontent-c3="">October</th><th _ngcontent-c3="">November</th><th _ngcontent-c3="">December</th>
</tr>
</thead>
<tbody _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2023</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td>
</tr><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2022</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">29</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">29</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td>
</tr><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2021</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">27</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td>
</tr><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2020</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">29</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td>
</tr><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2019</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="orange_Pava" ng-reflect-ng-class="orange_Pava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">20</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">25</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td>
</tr><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2018</span>
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">29</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">28</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">27</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">30</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td><td _ngcontent-c3="" class="green_Ava" ng-reflect-ng-class="green_Ava" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">31</span>
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
</td>
</tr><tr _ngcontent-c3="">
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><td _ngcontent-c3="" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">2017</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>
</td><td _ngcontent-c3="" class="white_NA" ng-reflect-ng-class="white_NA" style="cursor: pointer;">
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
<!--bindings={
  "ng-reflect-ng-if": "true"
}--><span _ngcontent-c3="">NA</span>

In [10]:
headers = []
rows = []
for tr in table.tbody.find_all('tr'):
    row = []
    for td in tr.find_all('td'):
        row.append(td.text.strip())
    rows.append(row)

for th in table.thead.find_all('th'):
    headers.append(th.text.strip())

In [11]:


df_1 = pd.DataFrame(rows, columns=headers)
df_1

,Year,January,February,March,April,May,June,July,August,September,October,November,December
0,2023,31,28,31,28,NA,NA,NA,NA,NA,NA,NA,NA
1,2022,31,28,31,30,31,30,31,29,30,31,29,31
2,2021,31,28,31,30,31,30,31,31,27,31,30,31
3,2020,31,29,31,30,31,30,31,31,30,31,30,31
4,2019,31,28,31,30,30,30,31,20,NA,25,30,31
5,2018,31,28,31,30,29,30,31,30,28,27,30,31
6,2017,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,7,31
7,2016,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
8,2015,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
9,2014,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
10,2013,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
11,2012,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
12,2011,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
13,2010,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
14,2009,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
15,2008,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
16,2007,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
17,2006,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA

In [18]:
df_1.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
Year,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006
January,31,31,31,31,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
February,28,28,28,29,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
March,31,31,3,30,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
April,28,30,NA,29,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
May,NA,31,NA,30,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
June,NA,30,NA,30,19,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
July,NA,31,NA,30,31,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
August,NA,31,NA,31,31,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
September,NA,30,NA,30,30,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
October,NA,31,3,31,31,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
November,NA,21,30,30,30,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
December,NA,14,30,31,31,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA

In [12]:
df_1.to_csv("./stations_start_info/dummy.csv", header=True, index=False)

In [24]:
import os
import pandas as pd
from time import sleep
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

df_1 = pd.read_csv('./processed_station_geo_loc.csv')
df_2 = pd.read_csv('./stations_region.csv')
df = pd.merge(df_1, df_2, on='name')
df.head()

df.sort_values(['state', 'city'], inplace=True)
df.reset_index(drop=True, inplace=True)

def fill_data(field_name, value):
    
    if field_name == 'state':
        field_box_click = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[1]'
        field_box_text = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/select-dropdown/div/div[1]/input'
        text = value
        
    elif field_name == 'city':
        field_box_click = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/div/div/div[1]'
        field_box_text = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/select-dropdown/div/div[1]/input'
        text = value
        
    elif field_name == 'station':
        field_box_click = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[3]/div/ng-select/div/div/div[1]'
        field_box_text = '/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[3]/div/ng-select/select-dropdown/div/div[1]/input'
        text = value
        
    if value=='Noida':
        field_box_click_action = driver.find_element_by_xpath(field_box_click)
        field_box_click_action.click()
        
        field_box_text_action = driver.find_element_by_xpath(field_box_text)
        field_box_text_action.send_keys(text)

        city_click = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[2]/div/ng-select/select-dropdown/div/div[2]/ul/li[2]')
        city_click.click()
        
    else:
        field_box_click_action = driver.find_element_by_xpath(field_box_click)
        field_box_click_action.click()

        field_box_text_action = driver.find_element_by_xpath(field_box_text)
        field_box_text_action.send_keys(text)

        field_box_text_action.send_keys(Keys.ENTER)
    

driver = webdriver.Chrome('/usr/bin/chromedriver')
sleep(10)
driver.get('https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing')
sleep(50)
driver.get('https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing/caaqm-data-availability')
sleep(15)

root_dir = "./stations_start_info"
if not os.path.exists(root_dir):
    os.mkdir(root_dir)
    
dummy_df = pd.read_csv(os.path.join(root_dir,"dummy.csv"))

error_idx = []
for idx in range(len(df)):
    
    if idx == 416:
    
        state = df.state[idx]
        city = df.city[idx]
        station_id = df.id[idx]
        station_name = df.name[idx]

        print(f"{idx}. {state} :: {city} :: {station_id} :: {station_name} :: ", end='')

        file_path = os.path.join(root_dir, state)
        if not os.path.exists(file_path):
            os.mkdir(file_path)

        try:
            # Find the button using XPath and click it
            # Clearing previous details filled in each field
            button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[2]')
            button.click()

            sleep(1)

            fill_data(field_name='state', value=state)
            sleep(1)
            fill_data(field_name='city', value=city)
            sleep(1)
            fill_data(field_name='station', value=station_name)
            sleep(1)

            # Find the button using XPath and click it
            button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[4]/div/button')
            button.click()

            sleep(35)

            soup = BeautifulSoup(driver.page_source, 'html.parser')
            table = soup.find('table', {'class': 'table-hover'})

            headers = []
            rows = []
            for tr in table.tbody.find_all('tr'):
                row = []
                for td in tr.find_all('td'):
                    row.append(td.text.strip())
                rows.append(row)

            for th in table.thead.find_all('th'):
                headers.append(th.text.strip())

            df_1 = pd.DataFrame(rows, columns=headers)

            if df_1.equals(dummy_df):
                print("ERROR", end='\n\n')
                error_idx.append(idx)
        #         break
            else:
                df_1.to_csv(os.path.join(file_path, city + '_' + station_id + '.csv'), header=True, index=False)
                print('Data Saved')
                dummy_df = df_1

        except:

            sleep(60)
            driver.get('https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing/caaqm-data-availability')
            sleep(15)
            # Find the button using XPath and click it
            # Clearing previous details filled in each field
            button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[1]/div/ng-select/div/div/div[2]')
            button.click()

            sleep(1)

            fill_data(field_name='state', value=state)
            sleep(1)
            fill_data(field_name='city', value=city)
            sleep(1)
            fill_data(field_name='station', value=station_name)
            sleep(1)

            # Find the button using XPath and click it
            button = driver.find_element_by_xpath('/html/body/app-root/app-caaqm-dashboard/div[1]/div/main/section/app-caaqm-data-availability/div/div/div/div/div/div/div[1]/div[4]/div/button')
            button.click()

            sleep(35)

            soup = BeautifulSoup(driver.page_source, 'html.parser')
            table = soup.find('table', {'class': 'table-hover'})

            headers = []
            rows = []
            for tr in table.tbody.find_all('tr'):
                row = []
                for td in tr.find_all('td'):
                    row.append(td.text.strip())
                rows.append(row)

            for th in table.thead.find_all('th'):
                headers.append(th.text.strip())

            df_1 = pd.DataFrame(rows, columns=headers)

            if df_1.equals(dummy_df):
                print("ERROR", end='\n\n')
                error_idx.append(idx)
        #         break
            else:
                df_1.to_csv(os.path.join(file_path, city + '_' + station_id + '.csv'), header=True, index=False)
                print('Data Saved')
                dummy_df = df_1
        
    
    
#     break

416. Uttar Pradesh :: Lucknow :: site_297 :: Talkatora District Industries Center, Lucknow - CPCB :: Data Saved

In [14]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
table = soup.find('table', {'class': 'table-hover'})

headers = []
rows = []
for tr in table.tbody.find_all('tr'):
    row = []
    for td in tr.find_all('td'):
        row.append(td.text.strip())
    rows.append(row)

for th in table.thead.find_all('th'):
    headers.append(th.text.strip())

df_1 = pd.DataFrame(rows, columns=headers)
df_1.to_csv(os.path.join(file_path, city + '_' + station_id + '.csv'), header=True, index=False)
print('Data Saved')

Data Saved

In [13]:
df_1

,Year,January,February,March,April,May,June,July,August,September,October,November,December
0,2023,31,28,31,30,NA,NA,NA,NA,NA,NA,NA,NA
1,2022,30,28,30,22,31,30,31,31,30,31,29,31
2,2021,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,9,31
3,2020,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,2019,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
5,2018,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
6,2017,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
7,2016,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
8,2015,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
9,2014,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
10,2013,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
11,2012,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
12,2011,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
13,2010,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
14,2009,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
15,2008,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
16,2007,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
17,2006,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA

In [8]:
import os
import pandas as pd
%config Completer.use_jedi=False

In [110]:
df = pd.read_csv("./stations_start_info/Assam/Byrnihat_site_5669.csv").T
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
Year,2023.0,2022.0,2021.0,2020.0,2019.0,2018.0,2017.0,2016.0,2015.0,2014.0,2013.0,2012.0,2011.0,2010.0,2009.0,2008.0,2007.0,2006.0
January,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
February,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
March,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
April,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
May,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
June,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
July,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
August,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
September,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
October,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
November,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
December,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
df = df.set_axis(df.iloc[0].astype(int), axis=1).drop(df.index[0])

In [112]:
df.isnull().sum()

Year
2023     8
2022    11
2021    12
2020    12
2019    12
2018    12
2017    12
2016    12
2015    12
2014    12
2013    12
2012    12
2011    12
2010    12
2009    12
2008    12
2007    12
2006    12
dtype: int64

In [113]:
df.columns

Int64Index([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013,
            2012, 2011, 2010, 2009, 2008, 2007, 2006],
           dtype='int64', name='Year')

In [114]:
df.index

Index(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype='object')

In [115]:
df

Year,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006
January,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
February,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
March,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
April,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
May,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
June,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
July,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
August,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
September,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
October,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
November,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
December,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df.dropna(axis=1, how='all', inplace=True)

In [117]:
df

Year       2023  2022
January    31.0   NaN
February   28.0   NaN
March      31.0   NaN
April      28.0   NaN
May         NaN   NaN
June        NaN   NaN
July        NaN   NaN
August      NaN   NaN
September   NaN   NaN
October     NaN   NaN
November    NaN   NaN
December    NaN  10.0

In [118]:
last_col = df.columns[-1]

In [119]:
last_col

2022

In [120]:
start_month = df[last_col].first_valid_index()

In [121]:
start_month

'December'

In [51]:
from glob import glob
import os
import pandas as pd
from datetime import datetime
%config Completer.use_jedi=False

In [52]:
df_1 = pd.read_csv('./processed_station_geo_loc.csv')
df_2 = pd.read_csv('./stations_region.csv')
df = pd.merge(df_1, df_2, on='name')
df.head()

,id,name,latitude,longitude,state,city
0,site_5094,"SIDCO Kurichi, Coimbatore - TNPCB",10.942451,76.978996,Tamil Nadu,Coimbatore
1,site_5261,"Muradpur, Patna - BSPCB",25.619651,85.147382,Bihar,Patna
2,site_5044,"Municipal Corporation Office, Dharuhera - HSPCB",28.206800,76.799700,Haryana,Dharuhera
3,site_5072,"Rishi Nagar, Kaithal - HSPCB",29.800600,76.415500,Haryana,Kaithal
4,site_163,"Peenya, Bengaluru - CPCB",13.027020,77.494094,Karnataka,Bengaluru

In [53]:
df.sort_values(['state', 'city'], inplace=True)
df.reset_index(drop=True, inplace=True)
df

,id,name,latitude,longitude,state,city
0,site_1406,"Secretariat, Amaravati - APPCB",16.515083,80.518167,Andhra Pradesh,Amaravati
1,site_5632,"Gulzarpet, Anantapur - APPCB",14.675886,77.593027,Andhra Pradesh,Anantapur
2,site_5665,"Gangineni Cheruvu, Chittoor - APPCB",13.204880,79.097889,Andhra Pradesh,Chittoor
3,site_5693,"Yerramukkapalli, Kadapa - APPCB",14.465052,78.824187,Andhra Pradesh,Kadapa
4,site_1399,"Anand Kala Kshetram, Rajamahendravaram - APPCB",16.987287,81.736318,Andhra Pradesh,Rajamahendravaram
...,...,...,...,...,...,...
456,site_5111,"Jadavpur, Kolkata - WBPCB",22.499290,88.369170,West Bengal,Kolkata
457,site_5126,"Rabindra Sarobar, Kolkata - WBPCB",22.511060,88.351420,West Bengal,Kolkata
458,site_5129,"Bidhannagar, Kolkata - WBPCB",22.581570,88.410025,West Bengal,Kolkata
459,site_5238,"Ballygunge, Kolkata - WBPCB",22.536751,88.363802,West Bengal,Kolkata
460,site_1419,"Ward-32 Bapupara, Siliguri - WBPCB",26.688305,88.412668,West Bengal,Siliguri

In [54]:
root_dir = "./stations_start_info"
start_date_data = []
for idx in range(len(df)):
    
    state = df.state[idx]
    city = df.city[idx]
    station_id = df.id[idx]
    station_name = df.name[idx]

    print(f"{idx}. {state} :: {city} :: {station_id} :: {station_name} :: ", end='')

    file_path = os.path.join(root_dir, state, city + '_' + station_id + '.csv')

    start_date_df = pd.read_csv(file_path).T
    start_date_df = start_date_df.set_axis(start_date_df.iloc[0].astype(int), axis=1).drop(start_date_df.index[0])
    start_date_df.dropna(axis=1, how='all', inplace=True)
    
    year_col = start_date_df.columns[-1]
    start_month = start_date_df[year_col].first_valid_index()
    month_number = datetime.strptime(start_month, '%B').month
    
    start_date_data.append([start_month,month_number, year_col])
#     break

0. Andhra Pradesh :: Amaravati :: site_1406 :: Secretariat, Amaravati - APPCB :: 1. Andhra Pradesh :: Anantapur :: site_5632 :: Gulzarpet, Anantapur - APPCB :: 2. Andhra Pradesh :: Chittoor :: site_5665 :: Gangineni Cheruvu, Chittoor - APPCB :: 3. Andhra Pradesh :: Kadapa :: site_5693 :: Yerramukkapalli, Kadapa - APPCB :: 4. Andhra Pradesh :: Rajamahendravaram :: site_1399 :: Anand Kala Kshetram, Rajamahendravaram - APPCB :: 5. Andhra Pradesh :: Tirupati :: site_258 :: Tirumala, Tirupati - APPCB :: 6. Andhra Pradesh :: Tirupati :: site_5666 :: Vaikuntapuram, Tirupati - APPCB :: 7. Andhra Pradesh :: Vijayawada :: site_257 :: PWD Grounds, Vijayawada - APPCB :: 8. Andhra Pradesh :: Vijayawada :: site_5685 :: Kanuru, Vijayawada - APPCB :: 9. Andhra Pradesh :: Visakhapatnam :: site_260 :: GVM Corporation, Visakhapatnam - APPCB :: 10. Arunachal Pradesh :: Naharlagun :: site_5446 :: Naharlagun, Naharlagun - APSPCB :: 11. Assam :: Byrnihat :: site_5669 :: Central Academy for SFS, Byrnihat - PCBA :: 12. Assam :: Guwahati :: site_5073 :: Railway Colony, Guwahati - PCBA :: 13. Assam :: Guwahati :: site_5417 :: Pan Bazaar, Guwahati - PCBA :: 14. Assam :: Guwahati :: site_5651 :: IITG, Guwahati - PCBA :: 15. Assam :: Guwahati :: site_5683 :: LGBI Airport, Guwahati - PCBA :: 16. Assam :: Nagaon :: site_5706 :: Christianpatty, Nagaon - PCBA :: 17. Assam :: Nalbari :: site_5668 :: Bata Chowk, Nalbari - PCBA :: 18. Assam :: Silchar :: site_5684 :: Tarapur, Silchar - PCBA :: 19. Assam :: Sivasagar :: site_5658 :: Girls College, Sivasagar - PCBA :: 20. Bihar :: Araria :: site_5539 :: Kharahiya Basti, Araria - BSPCB :: 21. Bihar :: Arrah :: site_5538 :: New DM Office, Arrah - BSPCB :: 22. Bihar :: Aurangabad :: site_5544 :: Gurdeo Nagar, Aurangabad - BSPCB :: 23. Bihar :: Begusarai :: site_5540 :: DRCC Anandpur, Begusarai - BSPCB :: 24. Bihar :: Bettiah :: site_5476 :: Kamalnath Nagar, Bettiah - BSPCB :: 25. Bihar :: Bhagalpur :: site_5541 :: Mayaganj, Bhagalpur - BSPCB :: 26. Bihar :: Bhagalpur :: site_5543 :: DM Office_Kachari Chowk, Bhagalpur - BSPCB :: 27. Bihar :: Bihar Sharif :: site_5481 :: D M Colony, Bihar Sharif - BSPCB :: 28. Bihar :: Buxar :: site_5542 :: Central Jail, Buxar - BSPCB :: 29. Bihar :: Chhapra :: site_5545 :: Darshan Nagar, Chhapra - BSPCB :: 30. Bihar :: Darbhanga :: site_5477 :: Town Hall - Lal Bagh, Darbhanga - BSPCB :: 31. Bihar :: Gaya :: site_159 :: Collectorate, Gaya - BSPCB :: 32. Bihar :: Gaya :: site_5338 :: SFTI Kusdihra, Gaya - BSPCB :: 33. Bihar :: Gaya :: site_5548 :: Kareemganj, Gaya - BSPCB :: 34. Bihar :: Hajipur :: site_5337 :: Industrial Area, Hajipur - BSPCB :: 35. Bihar :: Katihar :: site_5546 :: Mirchaibari, Katihar - BSPCB :: 36. Bihar :: Kishanganj :: site_5547 :: SDM Office_Khagra, Kishanganj - BSPCB :: 37. Bihar :: Manguraha :: site_5550 :: Forest Rest House, Manguraha - BSPCB :: 38. Bihar :: Motihari :: site_5478 :: Gandak Colony, Motihari - BSPCB :: 39. Bihar :: Munger :: site_5490 :: Town Hall, Munger - BSPCB :: 40. Bihar :: Muzaffarpur :: site_158 :: Muzaffarpur Collectorate, Muzaffarpur - BSPCB :: 41. Bihar :: Muzaffarpur :: site_5370 :: Buddha Colony, Muzaffarpur - BSPCB :: 42. Bihar :: Muzaffarpur :: site_5479 :: MIT-Daudpur Kothi, Muzaffarpur - BSPCB :: 43. Bihar :: Patna :: site_5261 :: Muradpur, Patna - BSPCB :: 44. Bihar :: Patna :: site_157 :: IGSC Planetarium Complex, Patna - BSPCB :: 45. Bihar :: Patna :: site_5262 :: Rajbansi Nagar, Patna - BSPCB :: 46. Bihar :: Patna :: site_5263 :: Samanpura, Patna - BSPCB :: 47. Bihar :: Patna :: site_5335 :: Govt. High School Shikarpur, Patna - BSPCB :: 48. Bihar :: Patna :: site_5336 :: DRM Office Danapur, Patna - BSPCB :: 49. Bihar :: Purnia :: site_5549 :: Mariam Nagar, Purnia - BSPCB :: 50. Bihar :: Rajgir :: site_5489 :: Dangi Tola, Rajgir - BSPCB :: 51. Bihar :: Saharsa :: site_5551 :: Police Line, Saharsa - BSPCB :: 52. Bihar :: Samastipur :: site_5552 :: DM Office_Kasipur, Samastipur - BSPCB :: 53. Bihar :: Sasaram :: site_5485 :: Dada Peer, Sasaram - BSPCB :: 54. Bihar :: Siwan :: site_5553 :: Chitragupta Nagar, Siwan - BSPCB :: 55. Chandigarh :: Chandigarh :: site_5127 :: Sector-25, Chandigarh - CPCC :: 56. Chandigarh :: Chandigarh :: site_5491 :: Sector 22, Chandigarh - CPCC :: 57. Chandigarh :: Chandigarh :: site_5582 :: Sector-53, Chandigarh - CPCC :: 58. Chhattisgarh :: Bhilai :: site_5536 :: Civic Center, Bhilai - Bhilai Steel Plant :: 59. Chhattisgarh :: Bhilai :: site_5659 :: Hathkhoj, Bhilai - CECB :: 60. Chhattisgarh :: Bhilai :: site_5660 :: 32Bungalows, Bhilai - CECB :: 61. Chhattisgarh :: Bilaspur :: site_5503 :: Mangala, Bilaspur - NTPC :: 62. Chhattisgarh :: Chhal :: site_5689 :: Nawapara SECL Colony, Chhal - CECB :: 63. Chhattisgarh :: Korba :: site_5656 :: Rampur, Korba - CECB :: 64. Chhattisgarh :: Korba :: site_5657 :: Urja Nagar, Korba - CECB :: 65. Chhattisgarh :: Kunjemura :: site_5690 :: OP Jindal School, Kunjemura - CECB :: 66. Chhattisgarh :: Milupara :: site_5691 :: Govt. Higher Secondary School, Milupara - CECB :: 67. Chhattisgarh :: Raipur :: site_5652 :: AIIMS, Raipur - CECB :: 68. Chhattisgarh :: Raipur :: site_5653 :: Siltara Phase-II, Raipur - CECB :: 69. Chhattisgarh :: Raipur :: site_5654 :: Krishak Nagar, Raipur - CECB :: 70. Chhattisgarh :: Raipur :: site_5655 :: Bhatagaon New ISBT, Raipur - CECB :: 71. Chhattisgarh :: Tumidih :: site_5692 :: OP Jindal Industrial Park, Tumidih - CECB :: 72. Delhi :: Delhi :: site_119 :: Sirifort, Delhi - CPCB :: 73. Delhi :: Delhi :: site_5395 :: Lodhi Road, Delhi - IITM :: 74. Delhi :: Delhi :: site_118 :: DTU, Delhi - CPCB :: 75. Delhi :: Delhi :: site_106 :: IGI Airport (T3), Delhi - IMD :: 76. Delhi :: Delhi :: site_107 :: Pusa, Delhi - IMD :: 77. Delhi :: Delhi :: site_108 :: Aya Nagar, Delhi - IMD :: 78. Delhi :: Delhi :: site_109 :: Lodhi Road, Delhi - IMD :: 79. Delhi :: Delhi :: site_115 :: NSIT Dwarka, Delhi - CPCB :: 80. Delhi :: Delhi :: site_117 :: ITO, Delhi - CPCB :: 81. Delhi :: Delhi :: site_103 :: CRRI Mathura Road, Delhi - IMD :: 82. Delhi :: Delhi :: site_105 :: North Campus, DU, Delhi - IMD :: 83. Delhi :: Delhi :: site_114 :: IHBAS, Dilshad Garden, Delhi - CPCB :: 84. Delhi :: Delhi :: site_104 :: Burari Crossing, Delhi - IMD :: 85. Delhi :: Delhi :: site_113 :: Shadipur, Delhi - CPCB :: 86. Delhi :: Delhi :: site_122 :: Mandir Marg, Delhi - DPCC :: 87. Delhi :: Delhi :: site_124 :: R K Puram, Delhi - DPCC :: 88. Delhi :: Delhi :: site_125 :: Punjabi Bagh, Delhi - DPCC :: 89. Delhi :: Delhi :: site_116 :: East Arjun Nagar, Delhi - CPCB :: 90. Delhi :: Delhi :: site_301 :: Anand Vihar, Delhi - DPCC :: 91. Delhi :: Delhi :: site_1420 :: Ashok Vihar, Delhi - DPCC :: 92. Delhi :: Delhi :: site_1421 :: Dr. Karni Singh Shooting Range, Delhi - DPCC :: 93. Delhi :: Delhi :: site_1422 :: Dwarka-Sector 8, Delhi - DPCC  :: 94. Delhi :: Delhi :: site_1423 :: Jahangirpuri, Delhi - DPCC :: 95. Delhi :: Delhi :: site_1424 :: Jawaharlal Nehru Stadium, Delhi - DPCC :: 96. Delhi :: Delhi :: site_1425 :: Major Dhyan Chand National Stadium, Delhi - DPCC :: 97. Delhi :: Delhi :: site_1426 :: Narela, Delhi - DPCC :: 98. Delhi :: Delhi :: site_1427 :: Najafgarh, Delhi - DPCC :: 99. Delhi :: Delhi :: site_1428 :: Okhla Phase-2, Delhi - DPCC :: 100. Delhi :: Delhi :: site_1429 :: Nehru Nagar, Delhi - DPCC :: 101. Delhi :: Delhi :: site_1430 :: Rohini, Delhi - DPCC :: 102. Delhi :: Delhi :: site_1431 :: Patparganj, Delhi - DPCC :: 103. Delhi :: Delhi :: site_1432 :: Sonia Vihar, Delhi - DPCC :: 104. Delhi :: Delhi :: site_1434 :: Wazirpur, Delhi - DPCC :: 105. Delhi :: Delhi :: site_1435 :: Vivek Vihar, Delhi - DPCC :: 106. Delhi :: Delhi :: site_1560 :: Bawana, Delhi - DPCC :: 107. Delhi :: Delhi :: site_1561 :: Mundka, Delhi - DPCC :: 108. Delhi :: Delhi :: site_1562 :: Sri Aurobindo Marg, Delhi - DPCC :: 109. Delhi :: Delhi :: site_1563 :: Pusa, Delhi - DPCC :: 110. Delhi :: Delhi :: site_5024 :: Alipur, Delhi - DPCC :: 111. Delhi :: Delhi :: site_5393 :: Chandni Chowk, Delhi - IITM :: 112. Gujarat :: Ahmedabad :: site_308 :: Maninagar, Ahmedabad - GPCB :: 113. Gujarat :: Ahmedabad :: site_5449 :: Sardar Vallabhbhai Patel Stadium, Ahmedabad - IITM :: 114. Gujarat :: Ahmedabad :: site_5450 :: Gyaspur, Ahmedabad - IITM :: 115. Gujarat :: Ahmedabad :: site_5451 :: Rakhial, Ahmedabad - IITM :: 116. Gujarat :: Ahmedabad :: site_5452 :: Raikhad, Ahmedabad - IITM :: 117. Gujarat :: Ahmedabad :: site_5453 :: Chandkheda, Ahmedabad - IITM :: 118. Gujarat :: Ahmedabad :: site_5454 :: SAC ISRO Bopal, Ahmedabad - IITM :: 119. Gujarat :: Ahmedabad :: site_5455 :: SAC ISRO Satellite, Ahmedabad - IITM :: 120. Gujarat :: Ahmedabad :: site_5456 :: SVPI Airport Hansol, Ahmedabad - IITM :: 121. Gujarat :: Ankleshwar :: site_5065 :: GIDC, Ankleshwar - GPCB :: 122. Gujarat :: Gandhinagar :: site_5066 :: Sector-10, Gandhinagar - GPCB :: 123. Gujarat :: Gandhinagar :: site_5457 :: IIPHG Lekawada, Gandhinagar - IITM :: 124. Gujarat :: Gandhinagar :: site_5458 :: GIFT City, Gandhinagar - IITM :: 125. Gujarat :: Nandesari :: site_5274 :: GIDC, Nandesari - Nandesari Ind. Association :: 126. Gujarat :: Surat :: site_5664 :: Science Center, Surat - SMC :: 127. Gujarat :: Vapi :: site_5071 :: Phase-1 GIDC, Vapi - GPCB :: 128. Gujarat :: Vatva :: site_5067 :: Phase-4 GIDC, Vatva - GPCB :: 129. Haryana :: Ambala :: site_5052 :: Patti Mehar, Ambala - HSPCB :: 130. Haryana :: Bahadurgarh :: site_5045 :: Arya Nagar, Bahadurgarh - HSPCB :: 131. Haryana :: Ballabgarh :: site_5060 :: Nathu Colony, Ballabgarh - HSPCB :: 132. Haryana :: Bhiwani :: site_5047 :: H.B. Colony, Bhiwani - HSPCB :: 133. Haryana :: Charkhi Dadri :: site_5339 :: Mini Secretariat, Charkhi Dadri - HSPCB :: 134. Haryana :: Dharuhera :: site_5044 :: Municipal Corporation Office, Dharuhera -  HSPCB :: 135. Haryana :: Faridabad :: site_263 :: Sector- 16A, Faridabad - HSPCB :: 136. Haryana :: Faridabad :: site_5340 :: New Industrial Town, Faridabad - HSPCB :: 137. Haryana :: Faridabad :: site_5341 :: Sector 30, Faridabad - HSPCB :: 138. Haryana :: Faridabad :: site_5342 :: Sector 11, Faridabad - HSPCB :: 139. Haryana :: Fatehabad :: site_5054 :: Huda Sector, Fatehabad - HSPCB :: 140. Haryana :: Gurugram :: site_5345 :: Sector-51, Gurugram - HSPCB :: 141. Haryana :: Gurugram :: site_146 :: Vikas Sadan, Gurugram - HSPCB :: 142. Haryana :: Gurugram :: site_5025 :: NISE Gwal Pahari, Gurugram - IMD :: 143. Haryana :: Gurugram :: site_5344 :: Teri Gram, Gurugram - HSPCB :: 144. Haryana :: Hisar :: site_5057 :: Urban Estate-II, Hisar - HSPCB :: 145. Haryana :: Jind :: site_5056 :: Police Lines, Jind - HSPCB :: 146. Haryana :: Kaithal :: site_5072 :: Rishi Nagar, Kaithal - HSPCB :: 147. Haryana :: Karnal :: site_5049 :: Sector-12, Karnal - HSPCB :: 148. Haryana :: Kurukshetra  :: site_5043 :: Sector-7, Kurukshetra - HSPCB :: 149. Haryana :: Mandikhera :: site_5055 :: General Hospital, Mandikhera - HSPCB :: 150. Haryana :: Manesar :: site_5039 :: Sector-2 IMT, Manesar - HSPCB :: 151. Haryana :: Narnaul :: site_5053 :: Shastri Nagar, Narnaul - HSPCB :: 152. Haryana :: Palwal  :: site_5050 :: Shyam Nagar, Palwal - HSPCB :: 153. Haryana :: Panchkula :: site_161 :: Sector-6, Panchkula - HSPCB  :: 154. Haryana :: Panipat :: site_5048 :: Sector-18, Panipat - HSPCB :: 155. Haryana :: Rohtak :: site_147 :: MD University, Rohtak - HSPCB :: 156. Haryana :: Sirsa :: site_5051 :: F-Block, Sirsa - HSPCB :: 157. Haryana :: Sonipat :: site_5041 :: Murthal, Sonipat - HSPCB :: 158. Haryana :: Yamuna Nagar :: site_5046 :: Gobind Pura, Yamuna Nagar - HSPCB :: 159. Himachal Pradesh :: Baddi :: site_5586 :: HIMUDA Complex Phase-1, Baddi - HPPCB :: 160. Jammu and Kashmir :: Srinagar :: site_5424 :: Rajbagh, Srinagar - JKSPCB :: 161. Jharkhand :: Dhanbad :: site_5710 :: Sardar Patel Nagar, Dhanbad - JSPCB :: 162. Jharkhand :: Jorapokhar :: site_254 :: Tata Stadium, Jorapokhar - JSPCB :: 163. Karnataka :: Bagalkot :: site_5264 :: Vidayagiri, Bagalkot - KSPCB :: 164. Karnataka :: Belgaum :: site_5432 :: Ramteerth Nagar, Belgaum - KSPCB :: 165. Karnataka :: Bengaluru :: site_163 :: Peenya, Bengaluru - CPCB :: 166. Karnataka :: Bengaluru :: site_1555 :: Hombegowda Nagar, Bengaluru - KSPCB :: 167. Karnataka :: Bengaluru :: site_164 :: BWSSB Kadabesanahalli, Bengaluru - CPCB :: 168. Karnataka :: Bengaluru :: site_165 :: City Railway Station, Bengaluru - KSPCB :: 169. Karnataka :: Bengaluru :: site_166 :: Sanegurava Halli, Bengaluru - KSPCB :: 170. Karnataka :: Bengaluru :: site_162 :: BTM Layout, Bengaluru - CPCB :: 171. Karnataka :: Bengaluru :: site_1553 :: Bapuji Nagar, Bengaluru - KSPCB :: 172. Karnataka :: Bengaluru :: site_1554 :: Hebbal, Bengaluru - KSPCB :: 173. Karnataka :: Bengaluru :: site_1556 :: Jayanagar 5th Block, Bengaluru - KSPCB :: 174. Karnataka :: Bengaluru :: site_1558 :: Silk Board, Bengaluru - KSPCB :: 175. Karnataka :: Bengaluru :: site_5678 :: RVCE-Mailasandra, Bengaluru - KSPCB ::

176. Karnataka :: Bengaluru :: site_5681 :: Kasturi Nagar, Bengaluru - KSPCB :: 177. Karnataka :: Bengaluru :: site_5686 :: Shivapura_Peenya, Bengaluru - KSPCB :: 178. Karnataka :: Bengaluru :: site_5729 :: Jigani, Bengaluru - KSPCB :: 179. Karnataka :: Bidar :: site_5418 :: Naubad, Bidar - KSPCB :: 180. Karnataka :: Chamarajanagar :: site_5124 :: Urban, Chamarajanagar - KSPCB :: 181. Karnataka :: Chikkaballapur :: site_1557 :: Chikkaballapur Rural, Chikkaballapur - KSPCB :: 182. Karnataka :: Chikkamagaluru :: site_5265 :: Kalyana Nagara, Chikkamagaluru - KSPCB :: 183. Karnataka :: Davanagere :: site_5422 :: Devaraj Urs Badavane, Davanagere - KSPCB :: 184. Karnataka :: Dharwad :: site_5638 :: Kalabhavan, Dharwad - KSPCB :: 185. Karnataka :: Gadag :: site_5419 :: Panchal Nagar, Gadag - KSPCB :: 186. Karnataka :: Hassan :: site_5448 :: B.Katihalli, Hassan - KSPCB :: 187. Karnataka :: Haveri :: site_5420 :: Ashwini Nagar, Haveri - KSPCB :: 188. Karnataka :: Hubballi :: site_1447 :: Deshpande Nagar, Hubballi - KSPCB :: 189. Karnataka :: Hubballi :: site_5680 :: Lingaraj Nagar, Hubballi - KSPCB :: 190. Karnataka :: Kalaburagi :: site_1565 :: Lal Bahadur Shastri Nagar, Kalaburagi - KSPCB :: 191. Karnataka :: Kalaburagi :: site_5679 :: Mahatma Basaveswar Colony, Kalaburgi - KSPCB :: 192. Karnataka :: Kolar :: site_1551 :: Tamaka Ind. Area, Kolar - KSPCB :: 193. Karnataka :: Koppal :: site_5415 :: Diwator Nagar, Koppal - KSPCB :: 194. Karnataka :: Madikeri :: site_5391 :: Stuart Hill, Madikeri - KSPCB :: 195. Karnataka :: Mangalore :: site_5421 :: Kadri, Mangalore - KSPCB :: 196. Karnataka :: Mysuru :: site_5125 :: Hebbal 1st Stage, Mysuru - KSPCB :: 197. Karnataka :: Raichur :: site_5414 :: Haji Colony, Raichur - KSPCB :: 198. Karnataka :: Ramanagara :: site_5255 :: Vijay Nagar, Ramanagara - KSPCB :: 199. Karnataka :: Shivamogga :: site_5266 :: Vinoba Nagara, Shivamogga - KSPCB :: 200. Karnataka :: Tumakuru :: site_5682 :: Thimmalapura, Tumakuru - KSPCB :: 201. Karnataka :: Udupi :: site_5433 :: Brahmagiri, Udupi - KSPCB :: 202. Karnataka :: Vijayapura :: site_5267 :: Ibrahimpur, Vijayapura - KSPCB :: 203. Karnataka :: Yadgir :: site_5254 :: Collector Office, Yadgir - KSPCB :: 204. Kerala :: Eloor :: site_5105 :: Udyogamandal, Eloor - Kerala PCB :: 205. Kerala :: Ernakulam :: site_5272 :: Kacheripady, Ernakulam - Kerala PCB :: 206. Kerala :: Kannur :: site_5276 :: Thavakkara, Kannur - Kerala PCB :: 207. Kerala :: Kochi :: site_5270 :: Vyttila, Kochi - Kerala PCB :: 208. Kerala :: Kollam :: site_5334 :: Polayathode, Kollam - Kerala PCB :: 209. Kerala :: Kozhikode :: site_5271 :: Palayam, Kozhikode - Kerala PCB :: 210. Kerala :: Thiruvananthapuram :: site_5331 :: Kariavattom, Thiruvananthapuram - Kerala PCB :: 211. Kerala :: Thiruvananthapuram :: site_252 :: Plammoodu, Thiruvananthapuram - Kerala PCB :: 212. Kerala :: Thrissur :: site_5390 :: Corporation Ground, Thrissur - Kerala PCB :: 213. Madhya Pradesh :: Bhopal :: site_5247 :: T T Nagar, Bhopal - MPPCB :: 214. Madhya Pradesh :: Bhopal :: site_5650 :: Paryavaran Parisar, Bhopal - MPPCB :: 215. Madhya Pradesh :: Bhopal :: site_5708 :: Idgah Hills, Bhopal - MPPCB :: 216. Madhya Pradesh :: Damoh :: site_5040 :: Shrivastav Colony, Damoh - MPPCB :: 217. Madhya Pradesh :: Dewas :: site_1404 :: Bhopal Chauraha, Dewas - MPPCB :: 218. Madhya Pradesh :: Gwalior :: site_5273 :: City Center, Gwalior - MPPCB :: 219. Madhya Pradesh :: Gwalior :: site_5275 :: Phool Bagh, Gwalior - Mondelez Ind. Food :: 220. Madhya Pradesh :: Gwalior :: site_5661 :: Maharaj Bada, Gwalior - MPPCB :: 221. Madhya Pradesh :: Gwalior :: site_5667 :: Deen Dayal Nagar, Gwalior - MPPCB :: 222. Madhya Pradesh :: Indore :: site_5248 :: Chhoti Gwaltoli, Indore - MPPCB :: 223. Madhya Pradesh :: Indore :: site_5709 :: Vijay Nagar Scheme-78, Indore - Glenmark :: 224. Madhya Pradesh :: Jabalpur :: site_5249 :: Marhatal, Jabalpur - MPPCB :: 225. Madhya Pradesh :: Katni :: site_5250 :: Gole Bazar, Katni - MPPCB :: 226. Madhya Pradesh :: Maihar :: site_5068 :: Sahilara, Maihar - KJS Cements :: 227. Madhya Pradesh :: Mandideep :: site_1403 :: Sector-D Industrial Area, Mandideep - MPPCB :: 228. Madhya Pradesh :: Pithampur :: site_1402 :: Sector-2 Industrial Area, Pithampur - MPPCB :: 229. Madhya Pradesh :: Ratlam :: site_5042 :: Shasthri Nagar, Ratlam - IPCA Lab :: 230. Madhya Pradesh :: Sagar :: site_5269 :: Deen Dayal Nagar, Sagar - MPPCB :: 231. Madhya Pradesh :: Sagar :: site_5662 :: Civil Lines, Sagar - MPPCB :: 232. Madhya Pradesh :: Satna :: site_1433 :: Bandhavgar Colony, Satna - Birla Cement :: 233. Madhya Pradesh :: Singrauli :: site_1401 :: Suryakiran Bhawan NCL, Singrauli - MPPCB :: 234. Madhya Pradesh :: Ujjain :: site_1400 :: Mahakaleshwar Temple, Ujjain - MPPCB :: 235. Maharashtra :: Aurangabad :: site_198 :: More Chowk Waluj, Aurangabad - MPCB :: 236. Maharashtra :: Chandrapur :: site_271 :: Chauhan Colony, Chandrapur - MPCB :: 237. Maharashtra :: Chandrapur :: site_295 :: MIDC Khutala, Chandrapur - MPCB :: 238. Maharashtra :: Kalyan :: site_5118 :: Khadakpada, Kalyan - MPCB :: 239. Maharashtra :: Kolhapur :: site_5768 :: Shivaji University, Kolhapur - MPCB :: 240. Maharashtra :: Kolhapur :: site_5769 :: Sinchan Bhavan, Kolhapur - MPCB :: 241. Maharashtra :: Mumbai :: site_5413 :: Mulund West, Mumbai - MPCB :: 242. Maharashtra :: Mumbai :: site_5396 :: Deonar, Mumbai - IITM :: 243. Maharashtra :: Mumbai :: site_5115 :: Worli, Mumbai - MPCB :: 244. Maharashtra :: Mumbai :: site_5412 :: Kandivali East, Mumbai - MPCB :: 245. Maharashtra :: Mumbai :: site_168 :: Bandra, Mumbai - MPCB :: 246. Maharashtra :: Mumbai :: site_5102 :: Vasai West, Mumbai - MPCB :: 247. Maharashtra :: Mumbai :: site_5104 :: Kurla, Mumbai - MPCB :: 248. Maharashtra :: Mumbai :: site_5106 :: Vile Parle West, Mumbai - MPCB :: 249. Maharashtra :: Mumbai :: site_5107 :: Chhatrapati Shivaji Intl. Airport (T2), Mumbai - MPCB :: 250. Maharashtra :: Mumbai :: site_5112 :: Powai, Mumbai - MPCB :: 251. Maharashtra :: Mumbai :: site_5113 :: Borivali East, Mumbai - MPCB :: 252. Maharashtra :: Mumbai :: site_5119 :: Sion, Mumbai - MPCB :: 253. Maharashtra :: Mumbai :: site_5120 :: Colaba, Mumbai - MPCB :: 254. Maharashtra :: Mumbai :: site_5392 :: Bandra Kurla Complex, Mumbai - IITM :: 255. Maharashtra :: Mumbai :: site_5394 :: Mazgaon, Mumbai - IITM :: 256. Maharashtra :: Mumbai :: site_5397 :: Khindipada-Bhandup West, Mumbai - IITM :: 257. Maharashtra :: Mumbai :: site_5398 :: Navy Nagar-Colaba, Mumbai - IITM :: 258. Maharashtra :: Mumbai :: site_5399 :: Chakala-Andheri East, Mumbai - IITM :: 259. Maharashtra :: Mumbai :: site_5400 :: Borivali East, Mumbai - IITM :: 260. Maharashtra :: Mumbai :: site_5402 :: Malad West, Mumbai - IITM :: 261. Maharashtra :: Mumbai :: site_5403 :: Siddharth Nagar-Worli, Mumbai - IITM :: 262. Maharashtra :: Nagpur :: site_303 :: Opp GPO Civil Lines, Nagpur - MPCB :: 263. Maharashtra :: Nashik :: site_304 :: Gangapur Road, Nashik - MPCB :: 264. Maharashtra :: Navi Mumbai :: site_261 :: Airoli, Navi Mumbai - MPCB :: 265. Maharashtra :: Navi Mumbai :: site_5103 :: Nerul, Navi Mumbai - MPCB :: 266. Maharashtra :: Navi Mumbai :: site_5114 :: Mahape, Navi Mumbai - MPCB :: 267. Maharashtra :: Navi Mumbai :: site_5401 :: Sector-19A Nerul, Navi Mumbai - IITM :: 268. Maharashtra :: Pune :: site_292 :: Karve Road, Pune - MPCB :: 269. Maharashtra :: Pune :: site_5404 :: Mhada Colony, Pune - IITM :: 270. Maharashtra :: Pune :: site_5405 :: Alandi, Pune - IITM :: 271. Maharashtra :: Pune :: site_5406 :: Bhosari, Pune - IITM :: 272. Maharashtra :: Pune :: site_5407 :: Hadapsar, Pune - IITM :: 273. Maharashtra :: Pune :: site_5408 :: Transport Nagar-Nigdi, Pune - IITM :: 274. Maharashtra :: Pune :: site_5409 :: Revenue Colony-Shivajinagar, Pune - IITM :: 275. Maharashtra :: Pune :: site_5410 :: MIT-Kothrud, Pune - IITM :: 276. Maharashtra :: Solapur :: site_302 :: Solapur, Solapur - MPCB :: 277. Maharashtra :: Thane :: site_305 :: Pimpleshwar Mandir, Thane - MPCB :: 278. Manipur :: Imphal :: site_5591 :: Manipur University, Imphal - Manipur PCB :: 279. Manipur :: Imphal :: site_5592 :: DM College of Science, Imphal - Manipur PCB :: 280. Meghalaya  :: Shillong :: site_5131 :: Lumpyngngad, Shillong - Meghalaya PCB :: 281. Meghalaya  :: Shillong :: site_5593 :: JN Stadium, Shillong - Meghalaya PCB :: 282. Mizoram :: Aizawl :: site_5346 :: Sikulpuikawn, Aizawl - Mizoram PCB :: 283. Nagaland :: Kohima :: site_5375 :: PWD Juction, Kohima - NPCB :: 284. Odisha :: Baripada :: site_5670 :: Meher Colony, Baripada - OSPCB :: 285. Odisha :: Bileipada :: site_5673 :: Tata Township, Bileipada - OSPCB :: 286. Odisha :: Brajrajnagar :: site_1410 :: GM Office, Brajrajnagar - OSPCB :: 287. Odisha :: Keonjhar :: site_5671 :: Jagamohanpur, Keonjhar - OSPCB :: 288. Odisha :: Nayagarh :: site_5674 :: Dabuna, Nayagarh - OSPCB :: 289. Odisha :: Rairangpur :: site_5672 :: Divisional Forest Office, Rairangpur - OSPCB :: 290. Odisha :: Rourkela :: site_5675 :: Raghunathpali, Rourkela - OSPCB :: 291. Odisha :: Rourkela :: site_5687 :: Fertilizer Township, Rourkela - OSPCB :: 292. Odisha :: Rourkela :: site_5688 :: Sector-2, Rourkela - OSPCB :: 293. Odisha :: Suakati :: site_5676 :: OMC Colony, Suakati - OSPCB :: 294. Odisha :: Talcher :: site_1408 :: Talcher Coalfields,Talcher - OSPCB :: 295. Odisha :: Tensa :: site_5677 :: Barsua Iron Ore Mines, Tensa - OSPCB :: 296. Puducherry :: Puducherry :: site_5423 :: Jawahar Nagar, Puducherry - PPCC :: 297. Punjab :: Amritsar :: site_256 :: Golden Temple, Amritsar - PPCB :: 298. Punjab :: Bathinda :: site_1549 :: Hardev Nagar, Bathinda - PPCB :: 299. Punjab :: Jalandhar :: site_1438 :: Civil Line, Jalandhar - PPCB :: 300. Punjab :: Khanna :: site_1450 :: Kalal Majra, Khanna - PPCB :: 301. Punjab :: Ludhiana :: site_253 :: Punjab Agricultural University, Ludhiana - PPCB :: 302. Punjab :: Mandi Gobindgarh :: site_255 :: RIMT University, Mandi Gobindgarh - PPCB :: 303. Punjab :: Patiala :: site_1437 :: Model Town, Patiala - PPCB :: 304. Punjab :: Rupnagar :: site_1538 :: Ratanpura, Rupnagar - Ambuja Cements :: 305. Rajasthan :: Ajmer :: site_1392 :: Civil Lines,  Ajmer - RSPCB :: 306. Rajasthan :: Alwar :: site_1390 :: Moti Doongri, Alwar - RSPCB :: 307. Rajasthan :: Banswara :: site_5711 :: Rati Talai, Banswara - RSPCB :: 308. Rajasthan :: Barmer :: site_5714 :: Railway Colony, Barmer - RSPCB :: 309. Rajasthan :: Bharatpur :: site_5695 :: Krishna Nagar, Bharatpur - RSPCB :: 310. Rajasthan :: Bhiwadi :: site_1391 :: RIICO Ind. Area III, Bhiwadi - RSPCB :: 311. Rajasthan :: Bikaner :: site_5696 :: MM Ground, Bikaner - RSPCB :: 312. Rajasthan :: Bundi :: site_5771 :: New Colony, Bundi - RSPCB :: 313. Rajasthan :: Chittorgarh :: site_5712 :: Shastri Nagar, Chittorgarh - RSPCB :: 314. Rajasthan :: Churu :: site_5699 :: Subash Chowk, Churu - RSPCB :: 315. Rajasthan :: Dausa :: site_5713 :: Khatikan Mohalla, Dausa - RSPCB :: 316. Rajasthan :: Dholpur :: site_5700 :: Raja Ganj, Dholpur - RSPCB :: 317. Rajasthan :: Hanumangarh :: site_5715 :: Housing Board, Hanumangarh - RSPCB :: 318. Rajasthan :: Jaipur :: site_134 :: Police Commissionerate, Jaipur - RSPCB :: 319. Rajasthan :: Jaipur :: site_1393 :: Adarsh Nagar, Jaipur - RSPCB :: 320. Rajasthan :: Jaipur :: site_1396 :: Shastri Nagar, Jaipur - RSPCB :: 321. Rajasthan :: Jaipur :: site_5725 :: Mansarovar Sector-12, Jaipur - RSPCB :: 322. Rajasthan :: Jaipur :: site_5727 :: Sector-2 Murlipura, Jaipur - RSPCB :: 323. Rajasthan :: Jaisalmer :: site_5772 :: Sadar Bazar, Jaisalmer - RSPCB :: 324. Rajasthan :: Jhalawar :: site_5724 :: Rajlaxmi Nagar, Jhalawar - RSPCB :: 325. Rajasthan :: Jhunjhunu :: site_5717 :: Indra Nagar, Jhunjhunu - RSPCB :: 326. Rajasthan :: Jodhpur :: site_136 :: Collectorate, Jodhpur - RSPCB :: 327. Rajasthan :: Jodhpur :: site_5694 :: Samrat Ashok Udhyan, Jodhpur - RSPCB :: 328. Rajasthan :: Jodhpur :: site_5720 :: Jhalamand, Jodhpur - RSPCB :: 329. Rajasthan :: Jodhpur :: site_5726 :: Digari Kalan, Jodhpur - RSPCB :: 330. Rajasthan :: Jodhpur :: site_5773 :: Mandor, Jodhpur - RSPCB :: 331. Rajasthan :: Karauli :: site_5723 :: Satyawati Vihar, Karauli - RSPCB :: 332. Rajasthan :: Kota :: site_1394 :: Shrinath Puram, Kota - RSPCB :: 333. Rajasthan :: Kota :: site_5701 :: Nayapura, Kota - RSPCB :: 334. Rajasthan :: Kota :: site_5707 :: Dhanmandi, Kota - RSPCB :: 335. Rajasthan :: Pali :: site_1395 :: Indira Colony Vistar, Pali - RSPCB :: 336. Rajasthan :: Pratapgarh :: site_5721 :: Pragati Nagar, Pratapgarh - RSPCB :: 337. Rajasthan :: Rajsamand :: site_5718 :: Dhoinda, Rajsamand - RSPCB ::

338. Rajasthan :: Sawai Madhopur :: site_5716 :: Sahu Nagar, Sawai Madhopur - RSPCB :: 339. Rajasthan :: Sikar :: site_5722 :: Radhakishan Pura, Sikar - RSPCB :: 340. Rajasthan :: Sirohi :: site_5705 :: Vedhaynath Colony, Sirohi - RSPCB :: 341. Rajasthan :: Sri Ganganagar :: site_5719 :: Old City, Sri Ganganagar - RSPCB :: 342. Rajasthan :: Tonk :: site_5702 :: Shastri Nagar, Tonk - RSPCB :: 343. Rajasthan :: Udaipur :: site_1397 :: Ashok Nagar, Udaipur - RSPCB :: 344. Sikkim :: Gangtok :: site_5590 :: Zero Point GICI, Gangtok - SSPCB :: 345. Tamil Nadu :: Ariyalur :: site_5606 :: Keelapalur, Ariyalur - TNPCB :: 346. Tamil Nadu :: Chengalpattu :: site_5605 :: Crescent University, Chengalpattu - TNPCB :: 347. Tamil Nadu :: Chennai :: site_288 :: Velachery Res. Area, Chennai - CPCB :: 348. Tamil Nadu :: Chennai :: site_5092 :: Manali Village, Chennai - TNPCB :: 349. Tamil Nadu :: Chennai :: site_306 :: Manali, Chennai - CPCB :: 350. Tamil Nadu :: Chennai :: site_5361 :: Arumbakkam, Chennai - TNPCB :: 351. Tamil Nadu :: Chennai :: site_5363 :: Perungudi, Chennai - TNPCB :: 352. Tamil Nadu :: Chennai :: site_5364 :: Royapuram, Chennai - TNPCB :: 353. Tamil Nadu :: Chennai :: site_5365 :: Kodungaiyur, Chennai - TNPCB :: 354. Tamil Nadu :: Chennai :: site_5618 :: Gandhi Nagar_Ennore, Chennai - TNPCB :: 355. Tamil Nadu :: Chennai :: site_293 :: Alandur Bus Depot, Chennai - CPCB :: 356. Tamil Nadu :: Coimbatore :: site_5094 :: SIDCO Kurichi, Coimbatore - TNPCB :: 357. Tamil Nadu :: Coimbatore :: site_5623 :: PSG College of Arts and Science, Coimbatore - TNPCB :: 358. Tamil Nadu :: Cuddalore :: site_5611 :: Semmandalam, Cuddalore - TNPCB :: 359. Tamil Nadu :: Cuddalore :: site_5621 :: Kudikadu, Cuddalore - TNPCB :: 360. Tamil Nadu :: Dindigul :: site_5608 :: Mendonsa Colony, Dindigul - TNPCB :: 361. Tamil Nadu :: Gummidipoondi :: site_5362 :: Anthoni Pillai Nagar, Gummidipoondi - TNPCB :: 362. Tamil Nadu :: Hosur :: site_5612 :: SIPCOT Phase-1, Hosur - TNPCB :: 363. Tamil Nadu :: Kanchipuram :: site_5619 :: Kilambi, Kanchipuram - TNPCB :: 364. Tamil Nadu :: Ooty :: site_5624 :: Bombay Castel, Ooty - TNPCB :: 365. Tamil Nadu :: Palkalaiperur :: site_5626 :: Bharathidasan University, Palkalaiperur - TNPCB :: 366. Tamil Nadu :: Ramanathapuram :: site_5625 :: Chalai Bazaar, Ramanathapuram - TNPCB :: 367. Tamil Nadu :: Salem :: site_5622 :: Sona College of Technology, Salem - TNPCB :: 368. Tamil Nadu :: Thoothukudi :: site_5367 :: Meelavittan, Thoothukudi - TNPCB :: 369. Tamil Nadu :: Tirupur :: site_5607 :: Kumaran College, Tirupur - TNPCB :: 370. Tamil Nadu :: Vellore :: site_5615 :: Vasanthapuram, Vellore - TNPCB :: 371. Telangana :: Hyderabad :: site_251 :: ICRISAT Patancheru, Hyderabad - TSPCB :: 372. Telangana :: Hyderabad :: site_262 :: Central University, Hyderabad - TSPCB :: 373. Telangana :: Hyderabad :: site_199 :: Bollaram Industrial Area, Hyderabad - TSPCB :: 374. Telangana :: Hyderabad :: site_275 :: IDA Pashamylaram, Hyderabad - TSPCB :: 375. Telangana :: Hyderabad :: site_294 :: Sanathnagar, Hyderabad - TSPCB :: 376. Telangana :: Hyderabad :: site_298 :: Zoo Park, Hyderabad - TSPCB :: 377. Telangana :: Hyderabad :: site_5595 :: New Malakpet, Hyderabad - TSPCB :: 378. Telangana :: Hyderabad :: site_5596 :: ECIL Kapra, Hyderabad - TSPCB :: 379. Telangana :: Hyderabad :: site_5597 :: IITH Kandi, Hyderabad - TSPCB :: 380. Telangana :: Hyderabad :: site_5598 :: Somajiguda, Hyderabad - TSPCB :: 381. Telangana :: Hyderabad :: site_5599 :: Kompally Municipal Office, Hyderabad - TSPCB :: 382. Telangana :: Hyderabad :: site_5600 :: Nacharam_TSIIC IALA, Hyderabad - TSPCB :: 383. Telangana :: Hyderabad :: site_5602 :: Ramachandrapuram, Hyderabad - TSPCB :: 384. Telangana :: Hyderabad :: site_5604 :: Kokapet, Hyderabad - TSPCB :: 385. Tripura :: Agartala :: site_5377 :: Kunjaban, Agartala - Tripura SPCB :: 386. Tripura :: Agartala :: site_5587 :: Bardowali, Agartala - Tripura SPCB :: 387. Uttar Pradesh :: Agra :: site_307 :: Sanjay Palace, Agra - UPPCB :: 388. Uttar Pradesh :: Agra :: site_5463 :: Shastripuram, Agra - UPPCB :: 389. Uttar Pradesh :: Agra :: site_5464 :: Manoharpur, Agra - UPPCB :: 390. Uttar Pradesh :: Agra :: site_5465 :: Sector-3B Avas Vikas Colony, Agra - UPPCB :: 391. Uttar Pradesh :: Agra :: site_5482 :: Rohta, Agra - UPPCB :: 392. Uttar Pradesh :: Agra :: site_5501 :: Shahjahan Garden, Agra - UPPCB :: 393. Uttar Pradesh :: Baghpat :: site_1569 :: New Collectorate, Baghpat - UPPCB :: 394. Uttar Pradesh :: Baghpat :: site_5585 :: Sardar Patel Inter College, Baghpat - UPPCB :: 395. Uttar Pradesh :: Bareilly :: site_5628 :: Civil Lines, Bareilly - UPPCB :: 396. Uttar Pradesh :: Bareilly :: site_5601 :: Rajendra Nagar, Bareilly - UPPCB :: 397. Uttar Pradesh :: Bulandshahr :: site_1542 :: Yamunapuram, Bulandshahr - UPPCB :: 398. Uttar Pradesh :: Firozabad :: site_5480 :: Nagla Bhau, Firozabad - UPPCB :: 399. Uttar Pradesh :: Firozabad :: site_5584 :: Vibhab Nagar, Firozabad - UPPCB :: 400. Uttar Pradesh :: Ghaziabad :: site_144 :: Vasundhara, Ghaziabad - UPPCB :: 401. Uttar Pradesh :: Ghaziabad :: site_5081 :: Sanjay Nagar, Ghaziabad - UPPCB :: 402. Uttar Pradesh :: Ghaziabad :: site_5082 :: Indirapuram, Ghaziabad - UPPCB :: 403. Uttar Pradesh :: Ghaziabad :: site_5083 :: Loni, Ghaziabad - UPPCB :: 404. Uttar Pradesh :: Gorakhpur :: site_5472 :: Madan Mohan Malaviya University of Technology, Gorakhpur - UPPCB :: 405. Uttar Pradesh :: Greater Noida :: site_1541 :: Knowledge Park - III, Greater Noida - UPPCB :: 406. Uttar Pradesh :: Greater Noida :: site_5121 :: Knowledge Park - V, Greater Noida - UPPCB :: 407. Uttar Pradesh :: Hapur :: site_5023 :: Anand Vihar, Hapur - UPPCB :: 408. Uttar Pradesh :: Jhansi :: site_5583 :: Shivaji Nagar, Jhansi - UPPCB :: 409. Uttar Pradesh :: Kanpur :: site_276 :: Nehru Nagar, Kanpur - UPPCB :: 410. Uttar Pradesh :: Kanpur :: site_5416 :: IITK, Kanpur - IITK :: 411. Uttar Pradesh :: Kanpur :: site_5474 :: NSI Kalyanpur, Kanpur - UPPCB :: 412. Uttar Pradesh :: Kanpur :: site_5500 :: FTI Kidwai Nagar, Kanpur - UPPCB :: 413. Uttar Pradesh :: Khurja :: site_5603 :: Kalindi Kunj, Khurja - UPPCB :: 414. Uttar Pradesh :: Lucknow :: site_272 :: Kendriya Vidyalaya, Lucknow - CPCB :: 415. Uttar Pradesh :: Lucknow :: site_277 :: Lalbagh, Lucknow - CPCB :: 416. Uttar Pradesh :: Lucknow :: site_297 :: Talkatora District Industries Center, Lucknow - CPCB :: 417. Uttar Pradesh :: Lucknow :: site_1405 :: Nishant Ganj, Lucknow - UPPCB :: 418. Uttar Pradesh :: Lucknow :: site_5128 :: Gomti Nagar, Lucknow - UPPCB :: 419. Uttar Pradesh :: Lucknow :: site_5460 :: B R Ambedkar University, Lucknow - UPPCB :: 420. Uttar Pradesh :: Lucknow :: site_5462 :: Kukrail Picnic Spot-1, Lucknow - UPPCB :: 421. Uttar Pradesh :: Meerut :: site_5109 :: Jai Bhim Nagar, Meerut - UPPCB :: 422. Uttar Pradesh :: Meerut :: site_5257 :: Pallavpuram Phase 2, Meerut - UPPCB :: 423. Uttar Pradesh :: Meerut :: site_5258 :: Ganga Nagar, Meerut - UPPCB :: 424. Uttar Pradesh :: Moradabad :: site_5613 :: Transport Nagar, Moradabad - UPPCB :: 425. Uttar Pradesh :: Moradabad :: site_1398 :: Lajpat Nagar, Moradabad - UPPCB :: 426. Uttar Pradesh :: Moradabad :: site_5537 :: Employment Office, Moradabad - UPPCB :: 427. Uttar Pradesh :: Moradabad :: site_5554 :: Buddhi Vihar, Moradabad - UPPCB :: 428. Uttar Pradesh :: Moradabad :: site_5555 :: Jigar Colony, Moradabad - UPPCB :: 429. Uttar Pradesh :: Moradabad :: site_5556 :: Eco Herbal Park, Moradabad - UPPCB :: 430. Uttar Pradesh :: Moradabad :: site_5620 :: Kashiram Nagar, Moradabad - UPPCB :: 431. Uttar Pradesh :: Muzaffarnagar :: site_1550 :: New Mandi, Muzaffarnagar - UPPCB :: 432. Uttar Pradesh :: Noida :: site_5123 :: Sector-1, Noida - UPPCB :: 433. Uttar Pradesh :: Noida :: site_153 :: Sector - 125, Noida - UPPCB :: 434. Uttar Pradesh :: Noida :: site_111 :: Sector - 62, Noida - IMD :: 435. Uttar Pradesh :: Noida :: site_5122 :: Sector-116, Noida - UPPCB :: 436. Uttar Pradesh :: Prayagraj :: site_5459 :: Motilal Nehru NIT, Prayagraj - UPPCB :: 437. Uttar Pradesh :: Prayagraj :: site_5461 :: Jhunsi, Prayagraj - UPPCB :: 438. Uttar Pradesh :: Prayagraj :: site_5484 :: Nagar Nigam, Prayagraj - UPPCB :: 439. Uttar Pradesh :: Varanasi :: site_5468 :: IESD Banaras Hindu University, Varanasi - UPPCB :: 440. Uttar Pradesh :: Varanasi :: site_273 :: Ardhali Bazar, Varanasi - UPPCB :: 441. Uttar Pradesh :: Varanasi :: site_5469 :: Bhelupur, Varanasi - UPPCB :: 442. Uttar Pradesh :: Varanasi :: site_5475 :: Maldahiya, Varanasi - UPPCB :: 443. Uttar Pradesh :: Vrindavan :: site_5483 :: Omex Eternity, Vrindavan - UPPCB :: 444. Uttarakhand :: Dehradun :: site_5594 :: Doon University, Dehradun - UKPCB :: 445. Uttarakhand :: Kashipur :: site_5704 :: Govt. Girls Inter College, Kashipur - UKPCB :: 446. Uttarakhand :: Rishikesh :: site_5703 :: Shivaji Nagar, Rishikesh - UKPCB :: 447. West Bengal :: Asansol :: site_1418 :: Asansol Court Area, Asansol - WBPCB :: 448. West Bengal :: Durgapur :: site_299 :: Sidhu Kanhu Indoor Stadium, Durgapur - WBPCB :: 449. West Bengal :: Haldia :: site_300 :: Priyambada Housing Estate, Haldia - WBPCB :: 450. West Bengal :: Howrah :: site_274 :: Ghusuri, Howrah - WBPCB :: 451. West Bengal :: Howrah :: site_1416 :: Padmapukur, Howrah - WBPCB :: 452. West Bengal :: Howrah :: site_5101 :: Belur Math, Howrah - WBPCB :: 453. West Bengal :: Kolkata :: site_296 :: Rabindra Bharati University, Kolkata - WBPCB :: 454. West Bengal :: Kolkata :: site_309 :: Victoria, Kolkata - WBPCB :: 455. West Bengal :: Kolkata :: site_5110 :: Fort William, Kolkata - WBPCB :: 456. West Bengal :: Kolkata :: site_5111 :: Jadavpur, Kolkata - WBPCB :: 457. West Bengal :: Kolkata :: site_5126 :: Rabindra Sarobar, Kolkata - WBPCB :: 458. West Bengal :: Kolkata :: site_5129 :: Bidhannagar, Kolkata - WBPCB :: 459. West Bengal :: Kolkata :: site_5238 :: Ballygunge, Kolkata - WBPCB :: 460. West Bengal :: Siliguri :: site_1419 :: Ward-32 Bapupara, Siliguri - WBPCB ::

In [55]:
start_date_data

[['November', 11, 2017],
 ['August', 8, 2022],
 ['November', 11, 2022],
 ['January', 1, 2023],
 ['September', 9, 2017],
 ['June', 6, 2016],
 ['November', 11, 2022],
 ['April', 4, 2017],
 ['January', 1, 2023],
 ['January', 1, 2017],
 ['March', 3, 2021],
 ['December', 12, 2022],
 ['February', 2, 2019],
 ['December', 12, 2020],
 ['September', 9, 2022],
 ['December', 12, 2022],
 ['February', 2, 2023],
 ['November', 11, 2022],
 ['January', 1, 2023],
 ['September', 9, 2022],
 ['November', 11, 2021],
 ['December', 12, 2021],
 ['November', 11, 2021],
 ['April', 4, 2022],
 ['July', 7, 2021],
 ['November', 11, 2021],
 ['November', 11, 2021],
 ['July', 7, 2021],
 ['November', 11, 2021],
 ['November', 11, 2021],
 ['July', 7, 2021],
 ['November', 11, 2015],
 ['February', 2, 2020],
 ['November', 11, 2021],
 ['February', 2, 2020],
 ['November', 11, 2021],
 ['November', 11, 2021],
 ['November', 11, 2021],
 ['July', 7, 2021],
 ['July', 7, 2021],
 ['September', 9, 2015],
 ['August', 8, 2020],
 ['July', 7, 2021],
 ['December', 12, 2019],
 ['June', 6, 2012],
 ['December', 12, 2019],
 ['December', 12, 2019],
 ['March', 3, 2020],
 ['February', 2, 2020],
 ['November', 11, 2021],
 ['July', 7, 2021],
 ['November', 11, 2021],
 ['March', 3, 2022],
 ['July', 7, 2021],
 ['November', 11, 2021],
 ['August', 8, 2019],
 ['August', 8, 2021],
 ['January', 1, 2022],
 ['November', 11, 2021],
 ['October', 10, 2022],
 ['October', 10, 2022],
 ['September', 9, 2021],
 ['January', 1, 2023],
 ['October', 10, 2022],
 ['October', 10, 2022],
 ['January', 1, 2023],
 ['January', 1, 2023],
 ['October', 10, 2022],
 ['October', 10, 2022],
 ['October', 10, 2022],
 ['October', 10, 2022],
 ['January', 1, 2023],
 ['January', 1, 2010],
 ['November', 11, 2020],
 ['January', 1, 2010],
 ['December', 12, 2013],
 ['May', 5, 2010],
 ['September', 9, 2010],
 ['January', 1, 2014],
 ['January', 1, 2010],
 ['January', 1, 2010],
 ['August', 8, 2010],
 ['February', 2, 2010],
 ['January', 1, 2010],
 ['March', 3, 2010],
 ['January', 1, 2010],
 ['April', 4, 2011],
 ['April', 4, 2011],
 ['April', 4, 2011],
 ['November', 11, 2017],
 ['July', 7, 2012],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['February', 2, 2018],
 ['July', 7, 2018],
 ['July', 7, 2018],
 ['July', 7, 2018],
 ['July', 7, 2018],
 ['November', 11, 2018],
 ['November', 11, 2020],
 ['October', 10, 2010],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['February', 2, 2019],
 ['February', 2, 2019],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['January', 1, 2020],
 ['November', 11, 2022],
 ['February', 2, 2019],
 ['February', 2, 2019],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['March', 3, 2020],
 ['January', 1, 2019],
 ['August', 8, 2010],
 ['March', 3, 2020],
 ['March', 3, 2020],
 ['March', 3, 2020],
 ['January', 1, 2019],
 ['March', 3, 2020],
 ['November', 11, 2015],
 ['October', 10, 2016],
 ['March', 3, 2020],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['February', 2, 2019],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['December', 12, 2018],
 ['January', 1, 2019],
 ['January', 1, 2019],
 ['November', 11, 2015],
 ['January', 1, 2019],
 ['December', 12, 2015],
 ['January', 1, 2019],
 ['December', 12, 2018],
 ['January', 1, 2019],
 ['March', 3, 2022],
 ['February', 2, 2021],
 ['February', 2, 2023],
 ['April', 4, 2017],
 ['January', 1, 2020],
 ['August', 8, 2022],
 ['January', 1, 2010],
 ['July', 7, 2018],
 ['January', 1, 2010],
 ['November', 11, 2015],
 ['November', 11, 2015],
 ['January', 1, 2010],
 ['June', 6, 2018],
 ['June', 6, 2018],
 ['June', 6, 2018],
 ['June', 6, 2018],
 ['December', 12, 2022],
 ['April', 4, 2023],
 ['February', 2, 2023],
 ['April', 4, 2023],
 ['January', 1, 2021],
 ['July', 7, 2019],
 ['June', 6, 2018],
 ['January', 1, 2020],
 ['January', 1, 2021],
 ['August', 8, 2022],
 ['January', 1, 2021],
 ['March', 3, 2021],
 ['April', 4, 2022],
 ['January', 1, 2015],
 ['December', 12, 2022],
 ['July', 7, 2018],
 ['December', 12, 2022],
 ['June', 6, 2018],
 ['December', 12, 2020],
 ['October', 10, 2020],
 ['January', 1, 2021],
 ['July', 7, 2019],
 ['December', 12, 2020],
 ['September', 9, 2019],
 ['January', 1, 2020],
 ['December', 12, 2022],
 ['February', 2, 2021],
 ['January', 1, 2020],
 ['September', 9, 2019],
 ['May', 5, 2019],
 ['January', 1, 2020],
 ['February', 2, 2020],
 ['January', 1, 2020],
 ['February', 2, 2020],
 ['January', 1, 2020],
 ['February', 2, 2020],
 ['June', 6, 2017],
 ['October', 10, 2020],
 ['September', 9, 2019],
 ['September', 9, 2022],
 ['February', 2, 2023],
 ['December', 12, 2018],
 ['November', 11, 2017],
 ['January', 1, 2020],
 ['January', 1, 2020],
 ['October', 10, 2022],
 ['December', 12, 2022],
 ['September', 9, 2019],
 ['March', 3, 2023],
 ['September', 9, 2019],
 ['September', 9, 2019],
 ['February', 2, 2019],
 ['January', 1, 2018],
 ['November', 11, 2017],
 ['December', 12, 2018],
 ['January', 1, 2020],
 ['October', 10, 2022],
 ['February', 2, 2018],
 ['December', 12, 2017],
 ['November', 11, 2017],
 ['September', 9, 2017],
 ['June', 6, 2015],
 ['August', 8, 2016],
 ['June', 6, 2019],
 ['April', 4, 2023],
 ['April', 4, 2023],
 ['December', 12, 2020],
 ['November', 11, 2020],
 ['June', 6, 2019],
 ['December', 12, 2020],
 ['January', 1, 2010],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['November', 11, 2020],
 ['November', 11, 2020],
 ['December', 12, 2020],
 ['November', 11, 2020],
 ['December', 12, 2020],
 ['November', 11, 2020],
 ['November', 11, 2020],
 ['January', 1, 2021],
 ['March', 3, 2016],
 ['April', 4, 2016],
 ['January', 1, 2010],
 ['June', 6, 2019],
 ['June', 6, 2019],
 ['November', 11, 2020],
 ['January', 1, 2010],
 ['November', 11, 2020],
 ['November', 11, 2020],
 ['November', 11, 2020],
 ['January', 1, 2021],
 ['November', 11, 2020],
 ['November', 11, 2020],
 ['January', 1, 2021],
 ['November', 11, 2015],
 ['August', 8, 2016],
 ['April', 4, 2022],
 ['April', 4, 2022],
 ['August', 8, 2019],
 ['April', 4, 2022],
 ['March', 3, 2020],
 ['September', 9, 2020],
 ['November', 11, 2022],
 ['November', 11, 2022],
 ['December', 12, 2017],
 ['November', 11, 2022],
 ['November', 11, 2022],
 ['November', 11, 2022],
 ['November', 11, 2022],
 ['January', 1, 2023],
 ['January', 1, 2023],
 ['November', 11, 2022],
 ['December', 12, 2017],
 ['November', 11, 2022],
 ['January', 1, 2021],
 ['February', 2, 2017],
 ['June', 6, 2018],
 ['February', 2, 2018],
 ['April', 4, 2018],
 ['April', 4, 2017],
 ['March', 3, 2017],
 ['February', 2, 2018],
 ['April', 4, 2018],
 ['October', 10, 2017],
 ['October', 10, 2017],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['October', 10, 2017],
 ['February', 2, 2023],
 ['April', 4, 2023],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['June', 6, 2017],
 ['October', 10, 2017],
 ['October', 10, 2017],
 ['March', 3, 2023],
 ['March', 3, 2023],
 ['April', 4, 2023],
 ['March', 3, 2023],
 ['March', 3, 2023],
 ['November', 11, 2015],
 ['February', 2, 2023],
 ['March', 3, 2023],
 ['April', 4, 2023],
 ['April', 4, 2023],
 ['March', 3, 2023],
 ['October', 10, 2017],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['October', 10, 2017],
 ['March', 3, 2023],
 ['March', 3, 2023],
 ['February', 2, 2023],
 ['March', 3, 2023],
 ['February', 2, 2023],
 ['March', 3, 2023],
 ['February', 2, 2023],
 ['October', 10, 2017],
 ['April', 4, 2022],
 ['December', 12, 2022],
 ['August', 8, 2022],
 ['January', 1, 2010],
 ['March', 3, 2019],
 ['January', 1, 2010],
 ['November', 11, 2020],
 ['December', 12, 2020],
 ['November', 11, 2020],
 ['November', 11, 2020],
 ['August', 8, 2022],
 ['January', 1, 2010],
 ['June', 6, 2019],
 ['September', 9, 2022],
 ['March', 3, 2023],
 ['March', 3, 2023],
 ['September', 9, 2022],
 ['January', 1, 2021],
 ['August', 8, 2022],
 ['October', 10, 2022],
 ['August', 8, 2022],
 ['March', 3, 2023],
 ['August', 8, 2022],
 ['August', 8, 2022],
 ['November', 11, 2020],
 ['August', 8, 2022],
 ['August', 8, 2022],
 ['February', 2, 2017],
 ['June', 6, 2017],
 ['February', 2, 2017],
 ['September', 9, 2016],
 ['November', 11, 2010],
 ['September', 9, 2015],
 ['May', 5, 2022],
 ['May', 5, 2022],
 ['May', 5, 2022],
 ['May', 5, 2022],
 ['May', 5, 2022],
 ['May', 5, 2022],
 ['June', 6, 2022],
 ['June', 6, 2022],
 ['November', 11, 2020],
 ['March', 3, 2022],
 ['September', 9, 2010],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['July', 7, 2021],
 ['September', 9, 2021],
 ['July', 7, 2018],
 ['January', 1, 2022],
 ['August', 8, 2022],
 ['May', 5, 2022],
 ['May', 5, 2018],
 ['July', 7, 2021],
 ['February', 2, 2022],
 ['September', 9, 2017],
 ['February', 2, 2019],
 ['February', 2, 2019],
 ['February', 2, 2019],
 ['June', 6, 2021],
 ['May', 5, 2018],
 ['June', 6, 2019],
 ['October', 10, 2018],
 ['February', 2, 2022],
 ['September', 9, 2010],
 ['December', 12, 2020],
 ['July', 7, 2021],
 ['September', 9, 2021],
 ['June', 6, 2022],
 ['January', 1, 2010],
 ['January', 1, 2010],
 ['January', 1, 2010],
 ['December', 12, 2017],
 ['August', 8, 2019],
 ['June', 6, 2021],
 ['July', 7, 2021],
 ['June', 6, 2019],
 ['October', 10, 2019],
 ['October', 10, 2019],
 ['June', 6, 2022],
 ['November', 11, 2017],
 ['November', 11, 2021],
 ['December', 12, 2021],
 ['December', 12, 2021],
 ['January', 1, 2022],
 ['June', 6, 2022],
 ['June', 6, 2018],
 ['June', 6, 2019],
 ['September', 9, 2017],
 ['December', 12, 2012],
 ['June', 6, 2019],
 ['June', 6, 2021],
 ['June', 6, 2021],
 ['July', 7, 2021],
 ['June', 6, 2021],
 ['September', 9, 2010],
 ['June', 6, 2021],
 ['July', 7, 2021],
 ['August', 8, 2021],
 ['April', 4, 2022],
 ['February', 2, 2023],
 ['February', 2, 2023],
 ['February', 2, 2018],
 ['June', 6, 2016],
 ['November', 11, 2015],
 ['December', 12, 2015],
 ['January', 1, 2018],
 ['May', 5, 2019],
 ['June', 6, 2016],
 ['December', 12, 2015],
 ['May', 5, 2019],
 ['June', 6, 2019],
 ['August', 8, 2019],
 ['August', 8, 2019],
 ['August', 8, 2019],
 ['February', 2, 2018]]

In [56]:
df_1 = pd.DataFrame(start_date_data, columns=['start_month', 'start_month_num', 'year'])

In [57]:
final_df = pd.concat([df, df_1], axis=1)
final_df

,id,name,latitude,longitude,state,city,start_month,start_month_num,year
0,site_1406,"Secretariat, Amaravati - APPCB",16.515083,80.518167,Andhra Pradesh,Amaravati,November,11,2017
1,site_5632,"Gulzarpet, Anantapur - APPCB",14.675886,77.593027,Andhra Pradesh,Anantapur,August,8,2022
2,site_5665,"Gangineni Cheruvu, Chittoor - APPCB",13.204880,79.097889,Andhra Pradesh,Chittoor,November,11,2022
3,site_5693,"Yerramukkapalli, Kadapa - APPCB",14.465052,78.824187,Andhra Pradesh,Kadapa,January,1,2023
4,site_1399,"Anand Kala Kshetram, Rajamahendravaram - APPCB",16.987287,81.736318,Andhra Pradesh,Rajamahendravaram,September,9,2017
...,...,...,...,...,...,...,...,...,...
456,site_5111,"Jadavpur, Kolkata - WBPCB",22.499290,88.369170,West Bengal,Kolkata,June,6,2019
457,site_5126,"Rabindra Sarobar, Kolkata - WBPCB",22.511060,88.351420,West Bengal,Kolkata,August,8,2019
458,site_5129,"Bidhannagar, Kolkata - WBPCB",22.581570,88.410025,West Bengal,Kolkata,August,8,2019
459,site_5238,"Ballygunge, Kolkata - WBPCB",22.536751,88.363802,West Bengal,Kolkata,August,8,2019
460,site_1419,"Ward-32 Bapupara, Siliguri - WBPCB",26.688305,88.412668,West Bengal,Siliguri,February,2,2018

In [58]:
final_df.to_csv('./stations_details.csv', header=True, index=False)

In [10]:
idx

35